### ISSUE TITLE
Custom domain with HTTPS

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-docker#3]
Feature request: HTTPS for custom domains. 

~~I expect the `WP_DOMAIN` defined in `.env` to be the site's domain after installation. The output from the `n install` script tells me so, too (`Open …`). The domain is not reachable, though, and the site can still only be accessed via `localhost`.~~

**Comment by leogermani** [comment]
it should be accessible by both localhost and your custom domain.

If you look at wp-config you'll see that siteurl and home are dynamically defined..

I got localhost on my .env but I access it using jurassic tube or ngrok and it works well. Is your tunneled domain not working?

**Comment by adekbadek** [comment]
My problem, as it turns out, was that I was assuming HTTPS would work out of the box. It does not. Custom domain with HTTP works (after editing the `/etc/hosts`  file), but not with HTTPS. I'll rescope the issue.
